apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true  # Добавьте эту опцию!
  project: system
  source:
    path: .
    repoURL: oci://registry-1.docker.io/bitnamicharts/mysql
    targetRevision: "14.0.3"
    helm:
      valuesObject:
        primary:
          configuration: |-
            [mysqld]
            authentication_policy='* ,,'
            skip-name-resolve
            explicit_defaults_for_timestamp
            basedir=/opt/bitnami/mysql
            plugin_dir=/opt/bitnami/mysql/lib/plugin
            port=3306
            mysqlx=0
            mysqlx_port=33060
            socket=/opt/bitnami/mysql/tmp/mysql.sock
            datadir=/bitnami/mysql/data
            tmpdir=/opt/bitnami/mysql/tmp
            bind-address=*
            pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
            log-error=/opt/bitnami/mysql/logs/mysqld.log
            character-set-server=UTF8
            slow_query_log=0
            long_query_time=10.0
            max_allowed_packet=64M
            innodb_buffer_pool_size=15G
            wait_timeout=14400
            interactive_timeout=14400
            net_read_timeout=60
            net_write_timeout=60
            binlog_expire_logs_seconds=604800
            max_connections=700

            [client]
            port=3306
            socket=/opt/bitnami/mysql/tmp/mysql.sock
            default-character-set=UTF8
            plugin_dir=/opt/bitnami/mysql/lib/plugin

            [manager]
            port=3306
            socket=/opt/bitnami/mysql/tmp/mysql.sock
            pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
          service:
            type: LoadBalancer
          persistence:
            size: 30Gi  
          resources:
            requests:
              cpu: 1
              memory: 0.5Gi
            limits:
              cpu: 2
              memory: 2Gi

  destination:
    name: "Dev Cluster"
    namespace: mysql
